name: Package latest
on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    steps:
    - name: Set environment variables
      id: env
      run: |
        eval "$(curl -sL --request GET \
          --url "https://api.github.com/repos/Radarr/Radarr/releases" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: token ${{ github.token }}" \
          | jq -r '.[0] | "export TAG=\(.tag_name) PRERELEASE=\(.prerelease)"')"
        
        echo "VERSION=${TAG//v}" >> $GITHUB_OUTPUT
        
        if [ ${PRERELEASE} ]; then
          echo "BRANCH=develop" >> $GITHUB_OUTPUT
        else
          echo "BRANCH=master" >> $GITHUB_OUTPUT
        fi

    - name: Check download link
      id: download
      run: |
        if [ -z "$(curl -sfL --request GET https://radarr.servarr.com/v1/update/${{ steps.env.outputs.BRANCH }}/updatefile?version=${{ steps.env.outputs.VERSION }}&os=linuxmusl&runtime=netcore&arch=x64)" ]; then
          echo "valid=true" >> "$GITHUB_OUTPUT"
        else
          echo "valid=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: ${{ steps.download.outputs.valid == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Sanitize repo slug
      uses: actions/github-script@v6
      id: repo_slug
      if: ${{ steps.download.outputs.valid == 'true' }}
      with:
        result-encoding: string
        script: return '${{ github.repository }}'.toLowerCase()

    - name: Check if image exists
      uses: tyriis/docker-image-tag-exists@v2.0.1
      id: image_exists
      if: ${{ steps.download.outputs.valid == 'true' }}
      with:
        registry: ghcr.io
        repository: ${{ steps.repo_slug.outputs.result }}
        tag: ${{ steps.env.outputs.VERSION }}
    
    - uses: actions/checkout@v4
      if: ${{ steps.download.outputs.valid == 'true' && steps.image_exists.outputs.tag != 'found' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: ${{ steps.download.outputs.valid == 'true' && steps.image_exists.outputs.tag != 'found' }}

    - name: Build and push
      uses: docker/build-push-action@v5
      if: ${{ steps.download.outputs.valid == 'true' && steps.image_exists.outputs.tag != 'found' }}
      with:
        build-args: |
          BRANCH=${{ steps.env.outputs.BRANCH }}
          VERSION=${{ steps.env.outputs.VERSION }}
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ steps.env.outputs.VERSION }}
          ghcr.io/${{ steps.repo_slug.outputs.result }}:latest
