
name: Publish the release
on:
  push:

jobs:
  publish-release:
    name: Publish releases
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          mytoken: ${{ github.token }}

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          prerelease: ${{ fromJSON(matrix.prerelease) }}
          name: ${{ matrix.version }}
          tag: ${{ matrix.tag }}
          body: |
            Changes in this Release: 
            ${{ steps.changelog.outputs.changelog }}